### ISSUE TITLE
Error when importing from app

### ISSUE THREAD

**Issue by nadavsinai** [JLHwung/webpack-dll-ng-module-loader#93] opened 2019-02-19 14:14 UTC
HI,
I'm trying to use your lib (angular 7.2.5 webpack 4.29.3)
I get this error when adding the import
````
import { WebpackDllNgModuleLoader } from "webpack-dll-ng-module-loader";
````
causes this:
````
   ERROR in (webpack)-dll-ng-module-loader/index.js 54:15
    Module parse failed: Unexpected token (54:15)
    You may need an appropriate loader to handle this file type.
    |             exportName = "default";
    |         }
    >         return import(module)
    |             .then(function (module) { return module[exportName]; })
    |             .then(function (type) { return checkNotEmpty(type, module, exportName); })
     @ ./src/app/app.module.ngfactory.js 17:9-54
     @ ./src/main.ts
     @ multi ./src/polyfills.ts ./src/main.ts
````
I cloned your repo and run the integration test and get the same result.
so it's not local to my app but perhaps inflicted by some environment stuff? I'm on Windows 10 x64
Any idea?
Thanks

**Comment by JLHwung** [comment] 2019-02-20 02:19
Hi Nadav,

The `unexpected token` refers to the `import()` call, typically due to webpack configuration issues.

As both Travis CI and me could not reproduce the issue you reported, could you offer a minimum reproduction repository? Otherwise there is no way to figure out what is going wrong here.

**Comment by nadavsinai** [comment] 2019-02-24 13:10
@JLHwung 	HI, thanks for your prompt response. 
the reproduction repo is your original repo as I stated  
"I cloned **your** repo and run the integration test and get the same result."
that's why i suggested it's maybe an environment issue (windows related?) ?

or otherwise - did you run your integration tests after greenkeeper (or whatever) upgraded your webpack version to 4.29.3 ((latest?)

I did try going to the actualy node_modules script of your lib and changing import to System.import which made the error go away, however lazy chunks are still not created/loaded and I get an error in runtime

**Comment by JLHwung** [comment] 2019-02-26 03:58
> did you run your integration tests after greenkeeper (or whatever) upgraded your webpack version to 4.29.3 ((latest?)

Yes I did, it works as expected. 

> environment issue (windows related?)

I do not have a Windows machine on hand, but at least I can spare some time to set up AppVeyor CI so that it can be tested against a Windows platform.

Let me know if you have more input.

**Comment by JLHwung** [comment] 2019-02-27 06:39
I setup appveyor on this project ([here](https://ci.appveyor.com/project/JLHwung/webpack-dll-ng-module-loader/builds/22679854)) and it looks like the integration test works on Windows, too. As the issue can not be reproduced at Appveyor, further information is in need, e.g. webpack configurations, environment variables, file structures.

**Comment by nadavsinai** [comment] 2019-03-10 20:56
Hi, sorry for the delay and thanks for your time. the error has been traced - caused by 
[webpack/webpack#8656](https://github.com/webpack/webpack/issues/8656)
it happens for me also with your integration - because I use NPM and not yarn.
the workaround @sokra suggests there works

**Comment by JLHwung** [comment] 2019-03-12 10:27
Hi, I am glad that your problem is solved. 

As you have mentioned that you use `npm` instead of `yarn` on integration test, I would like to say this is exactly the purpose of a reproduction repository, in which you can document exactly the reproduction step. Note that Dbuggerx also clearly lists the reproduction step on https://github.com/webpack/webpack/issues/8656. Anyway, no offense here and thank you very much for let me know the culprit here is incorrect dependency trees. This one is interesting.

I will close the issue now since it is not related to this library itself.

**Closed by JLHwung** 2019-03-12 10:27 UTC
Labels: question
